export const API_KEY_HERE = '8fea179a05b01ccd71d8f1d826bbdfc3';
export const baseURL = 'https://api.themoviedb.org/3'
export const imgURL = 'https://image.tmdb.org/t/p/w1280'
export const tendingmovies = `/trending/movie/week?api_key=${API_KEY_HERE}&language=en-US`
export const popularimgURL = `/movie/popular?api_key=${API_KEY_HERE}&language=en-US`
export const topratedURL = `/movie/top_rated?api_key=${API_KEY_HERE}&language=en-US`
export const upcomingURL = `/movie/upcoming?api_key=${API_KEY_HERE}&language=en-US`
export const netflixorginals = `/discover/movie?api_key=${API_KEY_HERE}&with_network=213`
export const actionmovies = `/discover/movie?api_key=${API_KEY_HERE}&with_genres=28`
export const comedymovies = `/discover/movie?api_key=${API_KEY_HERE}&with_genres=35`
export const horrormovies = `/discover/movie?api_key=${API_KEY_HERE}&with_genres=27`
export const romancemovies = `/discover/movie?api_key=${API_KEY_HERE}&with_genres=10749`
export const documentarymovies = `/discover/movie?api_key=${API_KEY_HERE}&with_genres=99`